from __future__ import annotations

"""
med3pipe.training.finetune

A thin wrapper to fine-tune SAM-Med3D using its native training script, but exposing a simple Python API.
We patch `utils/data_paths.py` temporarily to point to your prepared dataset folder and spawn `train.py`.

Notes
- This function runs a subprocess for training because `train.py` parses argv at import time.
- Keep `num_epochs` small for smoke tests; real fine-tuning can take hours.
- Requires that SAM-Med3D repo is available locally (see med3pipe.data.prepare.find_default_sam3d_root).
"""

from contextlib import contextmanager
from pathlib import Path
from typing import Iterable, Optional, Sequence
import os
import shutil
import subprocess
import sys

from ..data.prepare import Sam3DPaths, find_default_sam3d_root


@contextmanager
def patch_sam3d_data_paths(sam3d_root: Path, dataset_paths: Sequence[Path]):
    """Temporarily patch SAM-Med3D `utils/data_paths.py` to point to `dataset_paths`.

    dataset_paths should be folders that contain `imagesTr/` and `labelsTr/`.
    """
    sam3d_root = Path(sam3d_root)
    dp = sam3d_root / "utils" / "data_paths.py"
    backup = dp.with_suffix(".py.bak")
    if not dp.exists():
        raise FileNotFoundError(f"Cannot locate data_paths.py at {dp}")

    txt = [
        "''' Auto-generated by med3pipe.training.finetune.patch_sam3d_data_paths '''\n",
        "import os.path as osp\n",
        "PROJ_DIR = osp.dirname(osp.dirname(__file__))\n",
        "img_datas = [\n",
    ]
    for p in dataset_paths:
        rel = Path(p)
        txt.append(f"    osp.join(PROJ_DIR, '{rel.as_posix()}'),\n")
    txt.append("]\n")

    original = dp.read_bytes()
    try:
        # Backup and write
        if not backup.exists():
            shutil.copy2(dp, backup)
        with open(dp, "w", encoding="utf-8") as f:
            f.writelines(txt)
        yield
    finally:
        # Restore original
        if backup.exists():
            with open(dp, "wb") as f:
                f.write(original)
            backup.unlink(missing_ok=True)


def finetune_sam3d(
    paths: Sam3DPaths,
    sam3d_root: Optional[Path] = None,
    model_type: str = "vit_b_ori",
    checkpoint: Optional[Path] = None,
    device: str = "cuda",
    work_dir: Optional[Path] = None,
    num_epochs: int = 2,
    batch_size: int = 4,
    lr: float = 8e-4,
    weight_decay: float = 0.1,
    gpu_ids: Sequence[int] = (0,),
    multi_gpu: bool = False,
    extra_args: Optional[Sequence[str]] = None,
) -> subprocess.Popen:
    """Fine-tune SAM-Med3D on the prepared dataset defined by `paths`.

    Returns a running Popen handle for the training subprocess. Wait with `proc.wait()`.
    """
    sam3d_root = sam3d_root or find_default_sam3d_root()
    dataset_dir = paths.train_root
    if not (dataset_dir / "imagesTr").exists():
        raise FileNotFoundError(f"Expected imagesTr under {dataset_dir}")

    # Train script path
    train_py = sam3d_root / "train.py"
    if not train_py.exists():
        raise FileNotFoundError(f"train.py not found under {sam3d_root}")

    # Work dir
    if work_dir is None:
        work_dir = sam3d_root / "work_dir"
    work_dir.mkdir(parents=True, exist_ok=True)

    # Build cmd
    cmd = [
        sys.executable,
        str(train_py),
        "--task_name", f"{paths.category}_{paths.ct_name}_ft",
        "--model_type", model_type,
        "--device", device,
        "--work_dir", str(work_dir),
        "--num_epochs", str(num_epochs),
        "--batch_size", str(batch_size),
        "--lr", str(lr),
        "--weight_decay", str(weight_decay),
        "--gpu_ids", *[str(i) for i in gpu_ids],
    ]
    if checkpoint is not None:
        cmd += ["--checkpoint", str(checkpoint)]
    if multi_gpu:
        cmd += ["--multi_gpu"]
    if extra_args:
        cmd += list(extra_args)

    # Patch data_paths.py and launch
    rel_dataset = dataset_dir.relative_to(sam3d_root)
    env = os.environ.copy()
    env["CUDA_VISIBLE_DEVICES"] = ",".join(str(i) for i in gpu_ids)
    # Fix OpenMP library conflict
    env["KMP_DUPLICATE_LIB_OK"] = "TRUE"

    proc: subprocess.Popen
    with patch_sam3d_data_paths(sam3d_root, [rel_dataset]):
        proc = subprocess.Popen(
            cmd, 
            cwd=str(sam3d_root), 
            env=env,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            bufsize=1
        )
    return proc
